/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.CP.BloodBankMangementSystem.UI;

import com.CP.BloodBankManagementSystem.DBUtil.DBConnection;
import com.CP.BloodBankManagementSystem.Service.DonorBloodService;
import com.CP.BloodBankManagementSystem.entity.Donor;
import com.CP.BloodBankManagementSystem.entity.DonorBlood;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Satish
 */
public class BloodGroupsForm extends javax.swing.JFrame {

    private final DBConnection conn;

    public BloodGroupsForm() throws ClassNotFoundException {
        initComponents();
        conn = new DBConnection();
        FillDonorCombo();
        FillBloodCombo();
        setTitle("Blood Group Form");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        pnl = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lbl_Name = new javax.swing.JLabel();
        lbl_TelNo = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        lbl_HAddr = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lWarning = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        cmbDonorName = new javax.swing.JComboBox();
        cmbBloodType = new javax.swing.JComboBox();
        spnBloodPacket = new javax.swing.JSpinner();
        donateDateChooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/FormHeader.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        pnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_Name.setText("Donor Name:");

        lbl_TelNo.setText("Blood Packet");

        lbl_Email.setText("Date:");

        lbl_HAddr.setText("Blood Type");

        jLabel15.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Manage Blood Groups Details");

        lWarning.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        lWarning.setForeground(java.awt.Color.blue);
        lWarning.setText("Warning");

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/save.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/CloseButton2.png"))); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        cmbDonorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDonorNameActionPerformed(evt);
            }
        });

        cmbBloodType.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lWarning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_TelNo)
                            .addComponent(lbl_Email)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_HAddr)
                                    .addComponent(lbl_Name))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                        .addComponent(cmbDonorName, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(131, 131, 131))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(donateDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(spnBloodPacket, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cmbBloodType, javax.swing.GroupLayout.Alignment.LEADING, 0, 49, Short.MAX_VALUE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(0, 47, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Name)
                            .addComponent(cmbDonorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_HAddr)
                            .addComponent(cmbBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_TelNo)
                            .addComponent(spnBloodPacket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Email))
                    .addComponent(donateDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lWarning))
                .addGap(257, 257, 257))
        );

        pnl.addTab("Blood Group", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(pnl)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
       
            if (Integer.parseInt(spnBloodPacket.getValue().toString())==0)
            {
                JOptionPane.showMessageDialog(this, "At least 1 blood packet must be saved");
            }else if(donateDateChooser.getDate()==null)
            {
                JOptionPane.showMessageDialog(this, "Please enter the date");
            }
            else
            {
                try {
                    java.util.Date donatedDate = donateDateChooser.getDate();
                    DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                    String datedon = df.format(donatedDate);
                    java.sql.Date sqldon= new java.sql.Date(donatedDate.getTime());                    
                    DonorBloodService donorBloodService = new DonorBloodService();
                    DonorBlood donorBlood = new DonorBlood();
                    donorBlood.setDonorName(cmbDonorName.getSelectedItem().toString());
                    donorBlood.setBloodGrp(cmbBloodType.getSelectedItem().toString());
                    donorBlood.setBloodPacket(Integer.parseInt(spnBloodPacket.getValue().toString()));
                    donorBlood.setDonotedDate(sqldon);
                    donorBloodService.insert(donorBlood);
                    JOptionPane.showMessageDialog(this, "Blood packets Added Successfully", "Add Blood Packets", JOptionPane.INFORMATION_MESSAGE);
                    clearAllFields();
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(BloodGroupsForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            
        } 
        
           
        
    

    }//GEN-LAST:event_saveButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Are you sure that you want to exit ?");
        System.out.println(showConfirmDialog);
        if (showConfirmDialog == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void cmbDonorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDonorNameActionPerformed
        try {
            searchDonorbyDID((String) cmbDonorName.getSelectedItem());
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_cmbDonorNameActionPerformed
    private void FillDonorCombo() {
        try {
            conn.open();
            String sql = "Select * from tbl_donor";
            PreparedStatement stmt = conn.initStatement(sql);
            ResultSet rst = stmt.executeQuery();
            while (rst.next()) {
                String donor = rst.getString("Name");
                cmbDonorName.addItem(donor);
            }

        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }

    private void FillBloodCombo() {
        try {
            conn.open();
            String sql = "Select * from tbl_blood_type";
            PreparedStatement stmt = conn.initStatement(sql);
            ResultSet rst = stmt.executeQuery();
            while (rst.next()) {
                String blood = rst.getString("Blood_Group");
                cmbBloodType.addItem(blood);
            }

        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }

    private void searchDonorbyDID(String name) throws ClassNotFoundException, SQLException {
        DonorBloodService ds = new DonorBloodService();
        Donor existingDonor = ds.searchDonor(name);
        if (existingDonor != null) {
            cmbBloodType.setSelectedItem(existingDonor.getBloodGrp());
        }
    }

    public void clearAllFields() {        
        cmbDonorName.setSelectedIndex(-1);
        cmbBloodType.setSelectedIndex(-1);
        spnBloodPacket.setValue(0);
        donateDateChooser.setDate(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BloodGroupsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {

                try {
                    new BloodGroupsForm().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(BloodGroupsForm.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbBloodType;
    private javax.swing.JComboBox cmbDonorName;
    private com.toedter.calendar.JDateChooser donateDateChooser;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lWarning;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_HAddr;
    private javax.swing.JLabel lbl_Name;
    private javax.swing.JLabel lbl_TelNo;
    private javax.swing.JTabbedPane pnl;
    private javax.swing.JButton saveButton;
    private javax.swing.JSpinner spnBloodPacket;
    // End of variables declaration//GEN-END:variables
}
